# Generated by Django 3.0.7 on 2020-07-09 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_project', '0002_auto_20200709_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradedassignment',
            name='sub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
