# Generated by Django 3.0.7 on 2020-07-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_project', '0003_auto_20200709_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='year',
            field=models.CharField(choices=[('p1', 'P1'), ('p2', 'P2'), ('e1', 'E1'), ('e2', 'E2'), ('e3', 'E3'), ('e4', 'E4')], default='e1', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(choices=[('cse', 'CSE'), ('mech', 'MECH'), ('chem', 'CHEM'), ('ece', 'ECE'), ('mme', 'MME'), ('civil', 'CIVIL'), ('puc', 'PUC')], default='cse', max_length=5),
        ),
    ]
