# Generated by Django 3.0.7 on 2020-07-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_project', '0004_auto_20200710_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='year',
            field=models.CharField(default='e1', max_length=2),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='branch',
            field=models.CharField(default='clg', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(choices=[('puc', 'PUC'), ('cse', 'CSE'), ('mech', 'MECH'), ('chem', 'CHEM'), ('ece', 'ECE'), ('mme', 'MME'), ('civil', 'CIVIL')], default='cse', max_length=5),
        ),
    ]
